### ISSUE TITLE
Error: Load failed. Found unsatisfied imports 

### ISSUE THREAD

**Issue by Zergunchik** [quen0n/FipperZero-DHT-Monitor#2]
When I run a fap file on FZ I get an error: Load Failed. Found unsatisfied imports. Is it due to API mismatches?

**Comment by quen0n** [comment]
This error occurs because the plugin uses features that are not available in your firmware. This will be fixed in future versions of the plugin.

**Comment by quen0n** [comment]
You can use Unleashed firmware and everything will work

**Comment by quen0n** [comment]
https://github.com/quen0n/FipperZero-DHT-Monitor/releases/tag/v1.1owf

**Comment by unrealsolver** [comment]
strtok is not enabled by default
