### ISSUE TITLE
DHT11 - Timeout

### ISSUE THREAD

**Issue by Cainor** [quen0n/FipperZero-DHT-Monitor#4]
Hey, thank you for what you are doing. Just facing a hopefully small issue.

I have the DHT11 and I have plugged directly like you have shown in the pictures. Created a new sensor in the app, and set the pin read to 10.

However, It does not seem to be able to get a reading. It is stuck at 
"Timeout"

What am I doing wrong?

**Comment by quen0n** [comment]
Hello. Most likely the sensor is not connected correctly or is defective. Check the correct connection, serviceability of the wires and the sensor

**Comment by Cainor** [comment]
Thank you for your response. I'll try it with my Arduino and get back to you once I reach home.

**Comment by Cainor** [comment]
Okay, just found out the issue. After reading more about the DHT11 I found the below image:
https://hackster.imgix.net/uploads/attachments/1121112/untitled_sketch_bb_v2r5RgH7Uz.png?auto=compress%2Cformat&w=1280&h=960&fit=max

Which means that I did the wiring wrongly. Previously, I put the 5v on the left pin.
